name: handyman_admin_flutter
description: A new Flutter project.

publish_to: 'none'

version: 3.4.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.6
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.7
  share_plus: ^7.1.0

  #Firebase
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_remote_config: ^4.2.7

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.2.1
  dotted_border: ^2.1.0

  #image:
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  multi_image_picker: ^4.8.1
  photo_view: ^0.14.0
  file_picker: ^5.5.0
  lottie: ^2.6.0

  #notifications:
  onesignal_flutter: ^5.0.3

  # Other
  flutter_html: ^3.0.0-alpha.5

  #map:
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  permission_handler: ^11.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

